name: Scala CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
        scala:
          - 2.13.5
          - 2.12.13

    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Run Tests
        run: sbt "++${{ matrix.scala }}; test"
