name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
          - 17
        scala:
          - 2.13.8
          - 2.12.15

    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run Tests
        run: sbt "++${{ matrix.scala }}; test"

  docs:
    runs-on: ubuntu-latest
    needs: ['test']
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main'"
    name: 'Documentation'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docs
        run: |
          sbt "bindings/doc"
          mv -v bindings/target/scala-2.13/api docs/
          ls -l docs
          ls -l docs/api

      - name: Sanity check
        run: |
          test -s docs/CNAME
          test -d docs/api
          test -s docs/api/index.html
          test -d docs/api/mythtv

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
